sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dpnEECJgFP11Kg4nInivF0+rzETIooZQFsYk2NxY+orR1zX5OABHo3+9InsTepPF1mGI/o3YiKYKO60+yUJZcLV89Xh5aDT76ViStO7hCvCvMm/PH4lFugmqJ0gFfbmLqrZOQxpzXo6VY9btozl2hcgJc96+EgAQoFfS+c2Twuhmi96+vIKMBBwYrQ2OT05gFoekXFQ6dGuuR336hAtHE2Cu/Xz2dx+NeU5067qn2cgibVh9ZX/1Jd83iYGudsZLq8EVYNfaMDstkyy0fs1bkKXotXEi+iAiUaaeUx3GcoV7sEb8/rlxfPIc0hMGVoVUofMYz5IILAgqG7mNxgQ26xEamn0gYGYayG/cUkJH9soN/IvfCDf07JcY82WZ2pxIYImh8Fe2qKNqiLfEmXmS/VVILK+Beb9oY2A3NlwNe8QCWq+8ekCl3gORFSX+wyS4Kj9psdZvcB4WLFS61kWB/7h28hb5jf5SCTGPqOkFNTMQn5DRwoDCT2If8ruVQoPqZCDaAnXW1rwnVZTIsbwGipfh62HyK9UmYHuORNO4LvMgy20y0GkW6wYPQ99H0ZXnMxOloQhKI+VqIqjmkmN0/GwkWSzozEHVlnOWK/KY8RhqrEFFaUiJOR+SAx2cKCfsvq2cmMzajlwh8Io9lHa2b3g3kjVJxJ6etVDplFcpNwU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/State-of-the-Union-Addresses_5032
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy